/* SETTINGS */
export const CHANGE_LOCALE = 'CHANGE_LOCALE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const LOGOUT_USER = 'LOGOUT_USER';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS';

export const PEOPLE_GET = 'PEOPLE_GET';
export const PEOPLE_GET_SUCCESS = 'PEOPLE_GET_SUCCESS';
export const PEOPLE_GET_ERROR = 'PEOPLE_GET_ERROR';
export const PEOPLE_COUNT_GET = 'PEOPLE_COUNT_GET';
export const PEOPLE_COUNT_GET_SUCCESS = 'PEOPLE_COUNT_GET_SUCCESS';
export const PEOPLE_COUNT_GET_ERROR = 'PEOPLE_COUNT_GET_ERROR';
export const PEOPLE_CASE_GET = 'PEOPLE_CASE_GET';
export const PEOPLE_CASE_GET_SUCCESS = 'PEOPLE_CASE_GET_SUCCESS';
export const PEOPLE_CASE_GET_ERROR = 'PEOPLE_CASE_GET_ERROR';
export const PEOPLE_ADD = 'PEOPLE_ADD';
export const PEOPLE_ADD_SUCCESS = 'PEOPLE_ADD_SUCCESS';
export const PEOPLE_ADD_ERROR = 'PEOPLE_ADD_ERROR';
export const PEOPLE_EDIT = 'PEOPLE_EDIT';
export const PEOPLE_EDIT_SUCCESS = 'PEOPLE_EDIT_SUCCESS';
export const PEOPLE_EDIT_ERROR = 'PEOPLE_EDIT_ERROR';
export const PEOPLE_GET_PER_PAGE = 'PEOPLE_GET_PER_PAGE';
export const PEOPLE_GET_PER_PAGE_SUCCESS = 'PEOPLE_GET_PER_PAGE_SUCCESS';
export const PEOPLE_GET_PER_PAGE_ERROR = 'PEOPLE_GET_PER_PAGE_ERROR';
export const COMBINED_CASE_GET = 'COMBINED_CASE_GET';
export const COMBINED_CASE_GET_SUCCESS = 'COMBINED_CASE_GET_SUCCESS';
export const COMBINED_CASE_GET_ERROR = 'COMBINED_CASE_GET_ERROR';

export const SAVED_META_FIELD_ADD = 'SAVED_META_FIELD_ADD';
export const SAVED_META_FIELD_ADD_SUCCESS = 'SAVED_META_FIELD_ADD_SUCCESS';
export const SAVED_META_FIELD_ADD_ERROR = 'SAVED_META_FIELD_ADD_ERROR';
export const PEOPLE_CASE_ADD = 'PEOPLE_CASE_ADD';
export const PEOPLE_CASE_ADD_ERROR = 'PEOPLE_CASE_ADD_ERROR';
export const PEOPLE_CASE_ADD_SUCCESS = 'PEOPLE_CASE_ADD_SUCCESS';
export const PEOPLE_CASE_EDIT = 'PEOPLE_CASE_EDIT';
export const PEOPLE_CASE_EDIT_ERROR = 'PEOPLE_CASE_EDIT_ERROR';
export const PEOPLE_CASE_EDIT_SUCCESS = 'PEOPLE_CASE_EDIT_SUCCESS';
export const COMBINED_CASE_ADD = 'COMBINED_CASE_ADD';
export const COMBINED_CASE_ADD_ERROR = 'COMBINED_CASE_ADD_ERROR';
export const COMBINED_CASE_ADD_SUCCESS = 'COMBINED_CASE_ADD_SUCCESS';
export const COMBINED_CASE_EDIT = 'COMBINED_CASE_EDIT';
export const COMBINED_CASE_EDIT_ERROR = 'COMBINED_CASE_EDIT_ERROR';
export const COMBINED_CASE_EDIT_SUCCESS = 'COMBINED_CASE_EDIT_SUCCESS';
export const COMBINED_CASE_REMOVE = 'COMBINED_CASE_REMOVE';
export const COMBINED_CASE_REMOVE_ERROR = 'COMBINED_CASE_REMOVE_ERROR';
export const COMBINED_CASE_REMOVE_SUCCESS = 'COMBINED_CASE_REMOVE_SUCCESS';


export const CATEGORY_GET = 'CATEGORY_GET';
export const CATEGORY_GET_SUCCESS = 'CATEGORY_GET_SUCCESS';
export const CATEGORY_GET_ERROR = 'CATEGORY_GET_ERROR';
export const CATEGORY_ADD = 'CATEGORY_ADD';
export const CATEGORY_ADD_SUCCESS = 'CATEGORY_ADD_SUCCESS';
export const CATEGORY_ADD_ERROR = 'CATEGORY_ADD_ERROR';
export const CATEGORY_EDIT = 'CATEGORY_EDIT';
export const CATEGORY_EDIT_SUCCESS = 'CATEGORY_EDIT_SUCCESS';
export const CATEGORY_EDIT_ERROR = 'CATEGORY_EDIT_ERROR';
export const CATEGORY_COUNT_GET = 'CATEGORY_COUNT_GET';
export const CATEGORY_COUNT_GET_ERROR = 'CATEGORY_COUNT_GET_ERROR';
export const CATEGORY_COUNT_GET_SUCCESS = 'CATEGORY_COUNT_GET_SUCCESS';
export const CATEGORY_GET_PER_PAGE = 'CATEGORY_GET_PER_PAGE';
export const CATEGORY_GET_PER_PAGE_SUCCESS = 'CATEGORY_GET_PER_PAGE_SUCCESS';
export const CATEGORY_GET_PER_PAGE_ERROR = 'CATEGORY_GET_PER_PAGE_ERROR';

export const CASETAG_GET = 'CASETAG_GET';
export const CASETAG_GET_SUCCESS = 'CASETAG_GET_SUCCESS';
export const CASETAG_GET_ERROR = 'CASETAG_GET_ERROR';
export const CASETAG_ADD = 'CASETAG_ADD';
export const CASETAG_ADD_SUCCESS = 'CASETAG_ADD_SUCCESS';
export const CASETAG_ADD_ERROR = 'CASETAG_ADD_ERROR';
export const CASETAG_EDIT = 'CASETAG_EDIT';
export const CASETAG_EDIT_SUCCESS = 'CASETAG_EDIT_SUCCESS';
export const CASETAG_EDIT_ERROR = 'CASETAG_EDIT_ERROR';
export const CASETAG_COUNT_GET = 'CASETAG_COUNT_GET';
export const CASETAG_COUNT_GET_ERROR = 'CASETAG_COUNT_GET_ERROR';
export const CASETAG_COUNT_GET_SUCCESS = 'CASETAG_COUNT_GET_SUCCESS';
export const CASETAG_GET_PER_PAGE = 'CASETAG_GET_PER_PAGE';
export const CASETAG_GET_PER_PAGE_SUCCESS = 'CASETAG_GET_PER_PAGE_SUCCESS';
export const CASETAG_GET_PER_PAGE_ERROR = 'CASETAG_GET_PER_PAGE_ERROR';

export const CATEGORY_SUB_CATEGORY_GET = 'CATEGORY_SUB_CATEGORY_GET';
export const CATEGORY_SUB_CATEGORY_GET_SUCCESS = 'CATEGORY_SUB_CATEGORY_GET_SUCCESS';
export const CATEGORY_SUB_CATEGORY_GET_ERROR = 'CATEGORY_SUB_CATEGORY_GET_ERROR';
export const SUB_CATEGORY_CATEGORY_GET = 'SUB_CATEGORY_CATEGORY_GET';
export const SUB_CATEGORY_CATEGORY_GET_SUCCESS = 'SUB_CATEGORY_CATEGORY_GET_SUCCESS';
export const SUB_CATEGORY_CATEGORY_GET_ERROR = 'SUB_CATEGORY_CATEGORY_GET_ERROR';
export const SUB_CATEGORY_ADD = 'SUB_CATEGORY_ADD';
export const SUB_CATEGORY_ADD_ERROR = 'SUB_CATEGORY_ADD_ERROR';
export const SUB_CATEGORY_ADD_SUCCESS = 'SUB_CATEGORY_ADD_SUCCESS';
export const SUB_CATEGORY_EDIT = 'SUB_CATEGORY_EDIT';
export const SUB_CATEGORY_EDIT_ERROR = 'SUB_CATEGORY_EDIT_ERROR';
export const SUB_CATEGORY_EDIT_SUCCESS = 'SUB_CATEGORY_EDIT_SUCCESS';
export const SUB_CATEGORY_CATEGORY_ARRAY_GET = 'SUB_CATEGORY_CATEGORY_ARRAY_GET';
export const SUB_CATEGORY_CATEGORY_ARRAY_GET_SUCCESS = 'SUB_CATEGORY_CATEGORY_ARRAY_GET_SUCCESS';
export const SUB_CATEGORY_CATEGORY_ARRAY_GET_ERROR = 'SUB_CATEGORY_CATEGORY_ARRAY_GET_ERROR';
export const SUB_CATEGORY_REMOVE = 'SUB_CATEGORY_REMOVE';
export const SUB_CATEGORY_REMOVE_ERROR = 'SUB_CATEGORY_REMOVE_ERROR';
export const SUB_CATEGORY_REMOVE_SUCCESS = 'SUB_CATEGORY_REMOVE_SUCCESS';

export const METAFIELD_GET = 'METAFIELD_GET';
export const METAFIELD_GET_SUCCESS = 'METAFIELD_GET_SUCCESS';
export const METAFIELD_GET_ERROR = 'METAFIELD_GET_ERROR';
export const METAFIELD_ADD = 'METAFIELD_ADD';
export const METAFIELD_ADD_SUCCESS = 'METAFIELD_ADD_SUCCESS';
export const METAFIELD_ADD_ERROR = 'METAFIELD_ADD_ERROR';
export const METAFIELD_EDIT = 'METAFIELD_EDIT';
export const METAFIELD_EDIT_SUCCESS = 'METAFIELD_EDIT_SUCCESS';
export const METAFIELD_EDIT_ERROR = 'METAFIELD_EDIT_ERROR';
export const METAFIELD_COUNT_GET = 'METAFIELD_COUNT_GET';
export const METAFIELD_COUNT_GET_ERROR = 'METAFIELD_COUNT_GET_ERROR';
export const METAFIELD_COUNT_GET_SUCCESS = 'METAFIELD_COUNT_GET_SUCCESS';
export const METAFIELD_GET_PER_PAGE = 'METAFIELD_GET_PER_PAGE';
export const METAFIELD_GET_PER_PAGE_SUCCESS = 'METAFIELD_GET_PER_PAGE_SUCCESS';
export const METAFIELD_GET_PER_PAGE_ERROR = 'METAFIELD_GET_PER_PAGE_ERROR';

export * from './menu/actions';
export * from './settings/actions';
export * from './auth/actions';
export * from './people/actions';
export * from './category/actions';
export * from './meta-fields/actions';
export * from './case-tag/actions';